project:
  type: website
  output-dir: _site

website:
  title: "Puerto Rico Road Trip"
  navbar:
    left:
      - href: itinerary.qmd
        text: Itinerary

format:
  html:
    theme:
      - cosmo
      - variables.scss
    toc: true
  pdf:
    documentclass: article
    geometry:
      - top=1in
      - bottom=1in
      - left=1in
      - right=1in
    number-sections: false
    fontsize: 11pt
    mainfont: Lato
